inherit_from:
  - .rubocop_todo.yml
  - # use the shared Yast defaults
  - /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Offense count: 82
Metrics/AbcSize:
  Max: 231

# Offense count: 15
Metrics/BlockNesting:
  Max: 5
# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 650

# Offense count: 30
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 152
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 110

# Offense count: 117
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 283

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1286

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 28
Metrics/PerceivedComplexity:
  Max: 54

# Offense count: 40
Style/Documentation:
  Enabled: false

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 147
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 11

