# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Offense count: 82
Metrics/AbcSize:
  Max: 231

# Offense count: 15
Metrics/BlockNesting:
  Max: 5
# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 650

# Offense count: 30
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 152
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 110

# Offense count: 117
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 283

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1286

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 28
Metrics/PerceivedComplexity:
  Max: 54

# Offense count: 40
Style/Documentation:
  Enabled: false

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 147
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 11

# Offense count: 9
# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'src/clients/dasd_proposal.rb'
    - 'src/clients/zfcp_proposal.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 4
Lint/EmptyWhen:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 29
# Configuration parameters: CountComments, Max, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/include/s390/dump/ui.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/iucvterminal/ui.rb'
    - 'src/include/s390/onpanic/ui.rb'
    - 'src/modules/DASDController.rb'
    - 'test/dasd_controller_test.rb'
    - 'test/ui_include_test.rb'
    - 'test/ui_onpanic_include_test.rb'
    - 'test/zfcp_controller_test.rb'

# Offense count: 3
Naming/AccessorMethodName:
  Exclude:
    - 'src/modules/IUCVTerminal.rb'

# Offense count: 9
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, 
#   AllowedAcronyms.
Naming/FileName:
  Exclude:
    - 'src/clients/iucvterminal-server.rb'
    - 'src/clients/s390-disk-controller.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/Dump.rb'
    - 'src/modules/IUCVTerminal.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/OnPanic.rb'
    - 'src/modules/Xpram.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 19
# Configuration parameters: .
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Security/YAMLLoad:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'src/include/s390/onpanic/ui.rb'

# Offense count: 14
Style/MultipleComparison:
  Exclude:
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/include/s390/dump/ui.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/onpanic/ui.rb'
    - 'src/include/s390/xpram/ui.rb'
    - 'src/include/s390/zfcp/dialogs.rb'
    - 'src/modules/Dump.rb'
