# Offense count: 9
# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'src/clients/dasd_proposal.rb'
    - 'src/clients/zfcp_proposal.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 144
# Cop supports --auto-correct.
# Configuration parameters: IndentationWidth.
Layout/Tab:
  Enabled: false

# Offense count: 4
Lint/EmptyWhen:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 29
# Configuration parameters: CountComments, Max, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/include/s390/dump/ui.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/iucvterminal/ui.rb'
    - 'src/include/s390/onpanic/ui.rb'
    - 'src/modules/DASDController.rb'
    - 'test/dasd_controller_test.rb'
    - 'test/ui_include_test.rb'
    - 'test/ui_onpanic_include_test.rb'
    - 'test/zfcp_controller_test.rb'

# Offense count: 3
Naming/AccessorMethodName:
  Exclude:
    - 'src/modules/IUCVTerminal.rb'

# Offense count: 9
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, 
#   AllowedAcronyms.
Naming/FileName:
  Exclude:
    - 'src/clients/iucvterminal-server.rb'
    - 'src/clients/s390-disk-controller.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/Dump.rb'
    - 'src/modules/IUCVTerminal.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/OnPanic.rb'
    - 'src/modules/Xpram.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 19
# Configuration parameters: .
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Security/YAMLLoad:
  Exclude:
    - 'src/modules/DASDController.rb'
    - 'src/modules/ZFCPController.rb'
    - 'test/test_helper.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SingleLineConditionsOnly, IncludeTernaryExpressions.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/zfcp/dialogs.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/Encoding:
  Exclude:
    - 'src/clients/dasd.rb'
    - 'src/clients/dasd_auto.rb'
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/modules/DASDController.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'src/include/s390/onpanic/ui.rb'

# Offense count: 17
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/iucvterminal/ui.rb'
    - 'src/include/s390/xpram/ui.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/Dump.rb'
    - 'src/modules/IUCVTerminal.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/OnPanic.rb'
    - 'src/modules/Xpram.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MultilineIfModifier:
  Exclude:
    - 'src/modules/ZFCPController.rb'

# Offense count: 14
Style/MultipleComparison:
  Exclude:
    - 'src/include/s390/dasd/dialogs.rb'
    - 'src/include/s390/dump/ui.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/onpanic/ui.rb'
    - 'src/include/s390/xpram/ui.rb'
    - 'src/include/s390/zfcp/dialogs.rb'
    - 'src/modules/Dump.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'src/include/s390/dasd/dialogs.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/UnneededSort:
  Exclude:
    - 'src/modules/IUCVTerminal.rb'
